services:
  bot:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
    command: ["python", "bot.py"]
    restart: unless-stopped

  proxy:
    build: .
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=redis://redis:6379/0
    networks:
      - default
      - nginx_proxy
    command: ["/app/proxy-bin"]
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped

networks:
  nginx_proxy:
    external: true
